### ISSUE TITLE
Feature Request: Vuex support?

### ISSUE THREAD

**Issue by songololo** [fiery-data/fiery-vue#1]
Glad to see another option developing for linking Vue to Firestore. Looks really promising.

A feature request: Any chance of a Vuex Store Plugin version so that the methods can be accessed and managed from within a Vuex Store?

**Comment by ClickerMonkey** [comment]
I don't know enough about Vuex to be able to provide meaningful functionality (I've used it once) - but I am more than happy to add support if you or someone else could outline how it could work.

fiery-vue is basically a thin wrapper around fiery-data which is plain JS/TS library... So creating a thin wrapper for Vuex support would not be difficult I imagine.

**Comment by ClickerMonkey** [comment]
@shongololo 

Checkout https://github.com/fiery-data/fiery-vuex when you can!
