### ISSUE TITLE
[Bug] 'once' option doesn't work with streams

### ISSUE THREAD

**Issue by nmf2** [fiery-data/fiery-vue#11]
Regardless of the value of the "once" option the collection keeps getting updates, that is the value of `collectionData` keeps changing. 

```
methods: {
  loadData() {
    const options = {
      key: 'id',
      exclude: ['id'],
      once: true,
      live: false, // also tried without this parameter
      stream: true,
      streamInitial: 10,
      streamMore: 10,
      onSuccess: (data) => {
        console.log('data', data.length)
        this.loading = false
      }
    }
    
    this.collectionData = this.$fiery(firestore.collection('somecollection'), options)
  }
}
```
`collectionData` and `loading` are values from 'data' in Vue. And the method `loadData()` is called only when the component is created or the user requests some kind of query.

**Comment by ClickerMonkey** [comment]
Streams don't support once - it sounds like you just want an array. The whole point of streams is to start seeing a collection at a point in time and as new items come in they're added, but it also allows you to look back further in the past. Sort of like a real-time message channel.

**Comment by nmf2** [comment]
I see. I was using it for pagination on a table but I guess that won't work.

I'm using streams because a friend of mine said he had a problem with the pagination you provide.

Anyways, I'll try with pagination itself and if it doesn't work I'll open another issue. Thank you!

**Comment by nmf2** [comment]
Also, if you could add this to the README.md I think it could be useful. Just specifically saying that 'once' won't work with Streams.

**Comment by ClickerMonkey** [comment]
I'll add it to the docs.

I fixed the pagination issue here https://github.com/fiery-data/fiery-data/commit/88cedc3f30cbb52a7a279b80a3b9c1d0c36ccdde you just need to also provide a `queryReverse` function that returns the opposite of `query` to make the `prev` functionality work.

**Comment by nmf2** [comment]
Great! That's awesome! Thank you!
