### ISSUE TITLE
[Bug] fiery + computed properties doesn't work

### ISSUE THREAD

**Issue by nmf2** [fiery-data/fiery-vue#12]
I basically copied and pasted your pagination example and the following happens:

- The computed property doesn't change but the callbacks work: OnSucess, OnMutate and OnPromise are all called. 
- Changing the computed variable `cars` to a data property and passing the options directly (not through `carsOptions`) seems to work fine.

**Comment by ClickerMonkey** [comment]
I suspect I know what the problem is, I updated the example to show how it should be used and an explanation as to why:

https://github.com/fiery-data/fiery-vue/blob/master/README.md#data-or-computed

**Comment by ClickerMonkey** [comment]
If you find my suggestion doesn't work, please re-open issue.

**Comment by nmf2** [comment]
Thanks for your speedy reply (as always).

I tried it out and it didn't really work but I found something interesting (I'd check out the code first):

So, the expected behavior was having a single id shown in the array and when I clicked "Change" the array should expand (right?), but what happened was that the array was empty even though the OnSucess callback was called and I saw data and an array containing an id on the console. Furthermore, when I clicked "Change" the callback showed two ids but what was displayed on the page was an array with a single id. 

```
<template lang="pug">
  #main
    span {{JSON.stringify(lawsuits.map(l => l.id), null, 2)}}
    div
      v-btn(@click="change") Change
</template>

<script>
import firebase from '../store/firebase'
const db = firebase.firestore
export default {
  fiery: true,

  data () {
    return {
      limit: 1
    }
  },

  computed: {
    lawsuits () {
      const { limit } = this

      const options = {
        onSuccess: (data) => {
          console.log('data', JSON.stringify(data.map(l => l.id), null, 2))
        }
      }

      return this.$fiery(db.collection('lawsuitsDone').limit(limit), options, 'lawsuits')
    }
  },

  methods: {
    change () {
      this.limit++
    }
  }
}
</script>
```

Here's some before and after clicking "Change":
![before](https://user-images.githubusercontent.com/15805140/59558953-cbb4b580-8fd3-11e9-845b-33977809044f.png)

![after](https://user-images.githubusercontent.com/15805140/59558963-e850ed80-8fd3-11e9-88bb-b35ae46d801f.png)

**Comment by magicseth** [comment]
I'm seeing very similar behavior, where the computed method is called, but the dom doesn't update.

**Comment by magicseth** [comment]
I seem to fix it by adding a success callback to the options.

**Comment by magicseth** [comment]
`  computed: {
    episodes() {
      const vm = this;
      let options = {
        onSuccess: () => {
          vm.$forceUpdate();
        }
      };
      return this.$fiery(
        fs.collection("episodes"),
        options,
        "episodes"
      );
    }
  },
`

**Comment by fermuch** [comment]
Sorry to revive an old thread, but I've been facing the same issue. Has there been any progress or a reason why the dom doesn't update unless a `$forceUpdate` is called?
