### ISSUE TITLE
[feature request] add onBefore callback

### ISSUE THREAD

**Issue by wujekbogdan** [fiery-data/fiery-vue#4]
It's great that there are  `onSuccess`, `onError`, `onRemove`, and `onMissing` callbacks, but there's one more callback missing - `onBefore` (not sure about the naming). It would be useful for handling loading states - especially for computed properties. It would trigger before firebase documents/collections are rebound.

[Here's an example I've implemented for `vuefire`](https://github.com/vuejs/vuefire/issues/208#issuecomment-423522848)

**Comment by arjendejong12** [comment]
I second this. This is very useful for loading states.

**Comment by ClickerMonkey** [comment]
How would this be any different than just placing the same code in the computed property before fiery is called?

**Comment by wujekbogdan** [comment]
> How would this be any different than just placing the same code in the computed property before fiery is called?

@ClickerMonkey

I think I don't get it. Could you paste a code snippet, please?

**Comment by ClickerMonkey** [comment]
```javascript
fiery: true,
data: () => ({
  loading: false,
}),
computed: {
  peopleOptions() {
    return {
      // other options
      onSuccess: () => this.loading = false
    };
  },
  people() {
    this.loading = true;
    return this.$fiery(fs.collection('people'), this.peopleOptions, 'people');
  )
}
```

**Comment by wujekbogdan** [comment]
@ClickerMonkey 
Thanks, now I understand, but this workaround is against Vue best practices. If you use [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue), it will cause ESlint errors because of the [vue/no-side-effects-in-computed-properties](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-side-effects-in-computed-properties.md) rule.

**Comment by ClickerMonkey** [comment]
Yeah I see what you mean. Functionally it's the same thing, but Vue doesn't like it.

**Comment by ClickerMonkey** [comment]
I think I'm going to implement a different callback, onPromise which is triggered when a new promise is created. You can then do loading = true and when the promise resolves do loading = false. This will also allow you to listen for errors when loading data.

**Comment by arjendejong12** [comment]
Thank you for implementing onPromise! I see that onPromise only handles the first time loading something from Firebase. Is there a way to also implement this for when a live update happens?

**Comment by wujekbogdan** [comment]
> Thank you for implementing onPromise! I see that onPromise only handles the first time loading something from Firebase. Is there a way to also implement this for when a live update happens?

+1

**Comment by ClickerMonkey** [comment]
Not really - onSuccess will have to be used for that... since live updates don't really have a "start" and "stop". They occur when they do, and they are "instant".
