### ISSUE TITLE
[feature request] make .uid property configurable.

### ISSUE THREAD

**Issue by wujekbogdan** [fiery-data/fiery-vue#5]
Currently all the records have an `.uid` property. In Vue, it's very common to use ids as `:key` attributes `v-for` loops. It's also very common to use object destructuring in `v-for` loops, for example:

``` html
<li v-for="{title, content, date, id} in posts" :key="id">
  {{ title }} {{ content }} {{ date  }}
</li>
```

WIth vue-fire we can't do it because the following code is not a valid JS code.

``` html
<li v-for="{title, content, date, .uid} in posts" :key=".uid">
  {{ title }} {{ content }} {{ date  }}
</li>
```

So we have to re-write the code as follows:

``` html
<li v-for="post in posts" :key="post['.uid']">
   {{ post.title }} {{ post.content }} {{ post.date  }}
</li>
```

It would be great it the `.uid` property was configurable. It could be done via `FieryVue.setGlobalOptions` like:

``` javascript
FieryVue.setGlobalOptions({
  uid: 'id'
});
```

Another idea is to set `enumerable` to `false` for these properties as they are not "noramal" properties. This is how [vuefire](https://github.com/vuejs/vuefire/tree/lerna/packages/vuefire) deals with id properties.

**Comment by ClickerMonkey** [comment]
Thanks for the suggestion! I'll think about it. Your suggestion is a good one, but the setGlobalOptions function is used for other things.

You can do this:

```javascript
FieryVue.setGlobalOptions({
  key: 'id',
  exclude: ['id'] // we don't want id to be sent on save. If you are using include everywhere, this isn't necessary
});
```

You can then use post.id (the id/key is the last part of the .uid) and that should suffice for now!

**Comment by arjendejong12** [comment]
I see this isn't possible when using FieryVuex because setGlobalOptions is not defined in that package. Is there a reason it hasn't been implemented?

**Comment by ClickerMonkey** [comment]
You should be able to do `import { setGlobalOptions } from 'fiery-vuex'` just fine.

**Comment by ClickerMonkey** [comment]
```
FieryVue.constants.PROP_UID = 'myId'
```

With version 0.9.0
