### ISSUE TITLE
[Bug] pager.prev() travels to the first page

### ISSUE THREAD

**Issue by yvhr** [fiery-data/fiery-vue#6]
First of all, thank you for working on this vue plugin, it's a life-saver. Unfortunately I stumbled upon a bug while working with pagination.

I have a collection of 6 items. I set up a pager on a computed property like so:
```javascript
postsPaginator () {
   return this.$fiery.pager(this.posts)
}
```
I set up, `posts` inside data. Because for some reasons, doing it in computed is not reactive (I can see in vue-devtools that the objects are fetched, but the computed can't seem to detect it)

I have a pagination table where I call `this.postsPaginator.next()` it's all doing good until I tried doing successive calls to `next()` and then `prev()`. Basically, here's the gist:

Given a
```javascript
fiery: true,
data () {
   const db = this.$store.getters.db
   return {
     posts: $fiery(db.collection('posts'), { query: posts => posts.orderBy('timestamp', 'desc').limit(1) }, 'posts')
   }
},
computed: {
   paginator () {
      return this.$fiery.pager(this.posts)
   }
}
```
While having a total of `6` documents on `posts` collection.
When:
```javascript
paginator.next()  // proceeds normally
paginator.next() // proceeds normally
paginator.next() // normal
paginator.prev() // resets back to page 0
paginator.prev() // No data
```
Weirdly enough, If I'm just executing a simultaneous `next()` and `prev()`, everthing's working fine. Only when I did a `prev()` call after 2 or more successive `next()`.

And one more thing, I'm logging `paginator.index` and it's showing the correct page that I'm in. But the contents of the fetched objects are on say index `3` (when hitting `prev()`) but the fetched object is from index `0`.

**Comment by ClickerMonkey** [comment]
Thank you for reporting this, I'm looking into it!

**Comment by ClickerMonkey** [comment]
I was able to replicate the issue in a test, a fix should be made shortly.

**Comment by ClickerMonkey** [comment]
Uh-oh, based on what I'm seeing it's not as straight forward as I was expecting:

https://github.com/angular/angularfire2/issues/1560
https://github.com/angular/angularfire2/issues/1353 (see last comment)

This require some new options... since ordering and limiting is done in the query function. I'll have to ponder about this for some time.

**Comment by tlebeitsuk** [comment]
Any update on this issue?

**Comment by jimmykane** [comment]
Same issue here!

**Comment by jimmykane** [comment]
Hey guys. Either I am doing something wrong or this is really an issue and I wonder how people manage to paginate to previous page. 

Any update @ClickerMonkey

**Comment by ClickerMonkey** [comment]
I'm working on this at the moment.

**Comment by NiNJAD3vel0per** [comment]
endBefore/endAt don't work properly. it works odd without startAt/startAfter.
This is a bug!!!

queryRef = ref
.orderBy(query.field)
.endBefore("4")
.limit(query.limit)
