### ISSUE TITLE
[Bug] Real-time updates no longer working when the end of the stream was reached

### ISSUE THREAD

**Issue by yvhr** [fiery-data/fiery-vue#8]
Didn't notice this at first. I have some sort of comment counter that is being displayed on an element. After enabling `stream` functionality. I noticed that the value is no longer updating when I add a new comment. I commented out the stream options: `stream`, `streamInitial`, and `streamMore`, reloaded my page. Everything's working fine again, but yeah the Streaming is gone.

**Comment by ClickerMonkey** [comment]
Can you share some code?

**Comment by yvhr** [comment]
Oh sorry forgot about the code. It was really straightforward, so I don't know what's actually happening.
```javascript
...
fiery: true,
data () {
 const $fiery = this.$fiery
 const $db = this.$store.getters.db
 const streamOptions = { stream: true, streamInitial: 1, streamMore: 1 }
 return {
  postsLoading: true,
  posts: $fiery($db.collection('posts'), {
   query: posts => posts.where('publish', '==', true).where('archive', '==', false).orderBy('timestamp', 'desc'),
   ...streamOptions,
   onSuccess () => {
    this.postsLoading = false
   }
  })
 }
}
```

**Comment by yvhr** [comment]
Apologies! I've done some experiments a bit. And it turns out the problem has nothing to do with fiery-vue. An error was occurring when I tried to `this.$fiery.more()`  when I've reached the end of the collection. @ClickerMonkey is there anyway to determine if I've reached the end? So I could stop my scrolledToBottom event from firing?

Closing this issue now.

**Comment by yvhr** [comment]
Reopening this issue again, I finally figured out why the reactivity is lost. Basically, after calling
```javascript
this.$fiery.more(this.posts)
```
When there are no more documents on the `posts` collection, `onError` will be called and at this point, real-time updates are no longer working.

- Is there anyway to check if there are no more documents so another `more` can be prevented?
- Is there any other way to let the last call to `more` fail gracefully without affecting existing firestore bindings?

I suppose I can use `QuerySnapshot.size` as a quick workaround but it seems better if it could be included on `FieryEntry` or something to avoid issuing an extra database read.

**Comment by ClickerMonkey** [comment]
Added `this.$fiery.hasMore(this.posts)` and also added measures to avoid errors being thrown.

**Comment by ClickerMonkey** [comment]
`more` will also return a rejected promise if called and there is no more.
