### ISSUE TITLE
this.$fiery.create() promise

### ISSUE THREAD

**Issue by arjendejong12** [fiery-data/fiery-vue#9]
Hey, is there a way to 'await' the creation of a document when using `this.$fiery.create` so that after the creation was successful, I could execute other functions (but only if it was successful)?

**Comment by ClickerMonkey** [comment]
The source code for create looks like this:

```
  const built: T = this.build(target, initial)

  if (built)
  {
    this.sync(built)
  }

  return built
```

`this.sync(built)` returns a promise, so you could simply do this:

```
var model = this.$fiery.build(...);
var promise = this.$fiery.sync(model);
```
